Added Cell level control for Table Borders
py-pdf/fpdf2 pull request #1285
Opened 2024-10-15 20:27 UTC by Kaustbh

Fixes : #1192

Implemented a new feature that allows granular, cell-level control over table borders. With this update, users can now define specific borders (left, right, top, bottom) for individual cells, offering greater customization when generating tables in PDFs.

**Checklist**:

- [ ] The GitHub pipeline is OK (green), 
      meaning that both `pylint` (static code analyzer) and `black` (code formatter) are happy with the changes of this PR.

- [ ] A unit test is covering the code added / modified by this PR

- [ ] This PR is ready to be merged 

- [ ] In case of a new feature, docstrings have been added, with also some documentation in the `docs/` folder

- [ ] A mention of the change is present in `CHANGELOG.md`

By submitting this pull request, I confirm that my contribution is made under the terms of the [GNU LGPL 3.0 license](https://github.com/py-pdf/fpdf2/blob/master/LICENSE).

2024-10-15 20:31 UTC, Kaustbh commented
Hi @Lucas-C, I have made a PR to know if I am doing it correctly it is not a complete implementation, please see the code change and give me suggestions.

2024-10-16 07:03 UTC, Lucas-C commented on fpdf/table.py
> +    border: Optional[Union[str, int, CellBordersLayout]]
```suggestion
    border: Optional[CellBordersLayout]
```

2024-10-16 07:04 UTC, Lucas-C commented on fpdf/table.py
> +            border,
```suggestion
            CellBordersLayout.coerce(border),
```
It's better to check if the value provided is valid early, and to always store an instance of `CellBordersLayout`.

2024-10-16 07:05 UTC, Lucas-C commented on fpdf/table.py
> +            border = CellBordersLayout.coerce(cell.border)
Not needed if you perform the call to `.coerce()` in `Row.cell()`

2024-10-16 07:05 UTC, Lucas-C commented on fpdf/table.py
> +                border2 = []
```suggestion
                borders = []
```

2024-10-16 07:08 UTC, Lucas-C commented
> Hi @Lucas-C, I have made a PR to know if I am doing it correctly it is not a complete implementation, please see the code change and give me suggestions.

Nice, thank you for creating a PR 🙂

I made a few comments.

On thing that should come next is to add unit tests! 🙂

2024-10-19 13:25 UTC, Kaustbh commented
Hi, I made the suggested changes, now how can I fix this pylint warning,
 `fpdf/table.py:255:4: R0911: Too many return statements (7/6) (too-many-return-statements)` 
which is caused because of additional `return str(border)`.

And please tell me where I should add the unit tests.

2024-10-21 06:42 UTC, Lucas-C commented
> Hi, I made the suggested changes, now how can I fix this pylint warning, `fpdf/table.py:255:4: R0911: Too many return statements (7/6) (too-many-return-statements)` which is caused because of additional `return str(border)`.

It now seems to be passing, but you have however 27 failing tests.

> And please tell me where I should add the unit tests.

You can add them in `test/table/test_table.py`.

2024-10-24 17:20 UTC, Kaustbh commented
Hi @Lucas-C, should I write test just like this? and for all the different values like, `right`, `top`,  etc.

```
def test_cell_border_left(tmp_path):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Times", size=5)
    with pdf.table( gutter_height=2, gutter_width=2) as table:

        for data_row in TABLE_DATA:
            row = table.row()
            for datum in data_row:
                row.cell(datum,border="left")
    assert_pdf_equal(pdf, HERE / "test_cell_border_left.pdf", tmp_path)
```

2024-10-26 10:27 UTC, Kaustbh commented
@Lucas-C is it the right way of writing the tests?

2024-10-26 19:07 UTC, Lucas-C commented
> Hi @Lucas-C, should I write test just like this? and for all the different values like, `right`, `top`, etc.

Yes, this look likes a good start 👍
As mentioned on https://py-pdf.github.io/fpdf2/Development.html, you can pass `generate=True` once to `assert_pdf_equal()` in order to generate a reference PDF file.

And testing many possible combination of values is also a good idea!

2024-10-27 19:27 UTC, Kaustbh commented
is it fine @Lucas-C ?

2024-10-30 07:03 UTC, Lucas-C commented on test/text/test_cell.py
> +def test_cell_border_none(tmp_path):
Could you regroup all or most of those tests in a single one, with one case per page, in order to limit the number of reference PDF files, please?

All the right/left/top/bottom cases could form a single unit test I think.

`inherit` should have its own dedicated unit test & reference file, but I think more cases should be tested:
* cell `border="INHERIT"` with various table `borders_layout` values
* cell `border="INHERIT"` with table `outer_border_width` set

2024-10-30 07:04 UTC, Lucas-C commented on fpdf/table.py
> +            border = CellBordersLayout.coerce(cell.border)
I do not think that those `hasattr` & `CellBordersLayout.coerce` calls are needed.

2024-10-30 07:07 UTC, Lucas-C requested changes
> is it fine @Lucas-C ?

There are a couple of minor things remaining to be fixed, and also could you please add a mention of this addition in the `CHANGELOG.md` file?

The I'll be happy to merge your PR 👍 🙂

2024-11-01 14:46 UTC, Kaustbh commented
Hi @Lucas-C,

Should I add documentation for this as well, or would it be better to address it in a new issue? Creating a separate issue might also be a good idea, as it would give me the opportunity to make an additional contribution 🙂

2024-11-01 20:19 UTC, Lucas-C commented
> Should I add documentation for this as well, or would it be better to address it in a new issue? Creating a separate issue might also be a good idea, as it would give me the opportunity to make an additional contribution 🙂

We usually integrate the documentation related to new features as part of the PR that introduced it, so yes, it would be a good idea to include some documentation as part of this PR 🙂

Also, have you seen my other previous comments regarding the remaing minor changes required?

2024-11-01 20:25 UTC, Kaustbh commented
Yes, I have made the changes you suggested.

2024-11-01 20:57 UTC, Lucas-C commented
> Yes, I have made the changes you suggested.

I'm sorry but I don't think you adressed all those points:
* https://github.com/py-pdf/fpdf2/pull/1285#discussion_r1821995647
* https://github.com/py-pdf/fpdf2/pull/1285#discussion_r1821993474

And I also previously wrote:

> also could you please add a mention of this addition in the CHANGELOG.md file?

> We usually integrate the documentation related to new features as part of the PR that introduced it, so yes, it would be a good idea to include some documentation as part of this PR 🙂

2024-11-01 21:04 UTC, Kaustbh commented
I haven't committed it yet.

2024-11-01 21:18 UTC, Lucas-C commented
> I haven't committed it yet.

Oh OK, alright, that's fine🙂
Take your time 👍

2024-11-06 18:28 UTC, Kaustbh commented
Hi @Lucas-C, I have made the changes and also added documentation. I'm sorry, but I was not able to render the API documentation on my laptop. Please review the code and let me know if any changes are required.

2024-11-06 19:14 UTC, Lucas-C commented on CHANGELOG.md
> +* support for overriding paragraph direction on bidirectional text
```suggestion
```
This line comes from release `2.7.9`

2024-11-06 19:15 UTC, Lucas-C commented on docs/Tables.md
> +            row.cell(datum, border=1) # Left
```suggestion
            row.cell(datum, border="LEFT")
```

2024-11-06 19:15 UTC, Lucas-C commented on docs/Tables.md
> +            row.cell(datum, border=4) # Top
```suggestion
            row.cell(datum, border="TOP")
```

2024-11-06 19:17 UTC, Lucas-C commented on docs/Tables.md
> +pdf = FPDF()
```suggestion
from fpdf import FPDF

pdf = FPDF()
```
We try to make all code snippets autonomous: you can copy paste it in a `.py` script and it should just work!
That's why including the imports is important 🙂

2024-11-06 19:17 UTC, Lucas-C commented on docs/Tables.md
> +pdf = FPDF()
```suggestion
from fpdf import FPDF

pdf = FPDF()
```
We try to make all code snippets autonomous: you can copy paste it in a `.py` script and it should just work!
That's why including the imports is important 🙂

2024-11-06 19:17 UTC, Lucas-C commented on docs/Tables.md
> +pdf = FPDF()
```suggestion
from fpdf import FPDF

pdf = FPDF()
```
We try to make all code snippets autonomous: you can copy paste it in a `.py` script and it should just work!
That's why including the imports is important 🙂

2024-11-06 19:22 UTC, Lucas-C commented on docs/Tables.md
> +            row.cell(datum, border=5) # Left + Top
```suggestion
            row.cell(datum, border=CellBordersLayout.TOP | CellBordersLayout.LEFT)
```

2024-11-06 19:25 UTC, Lucas-C commented on fpdf/table.py
> +            border = CellBordersLayout.coerce(cell.border)
I tested on your branch, an lines 264 to 268 can be replaced by:
```python
        if cell.border != CellBordersLayout.INHERIT:
            return str(cell.border)
```

2024-11-06 19:29 UTC, Lucas-C approved these changes
Good job overall 👍 👍 👍

You wrote really good code, good documentation and good tests!

There are only a few minor details remaining:
* this early comment I made that I think you might have missed: https://github.com/py-pdf/fpdf2/pull/1285#discussion_r1831595402
* an extra line in `CHANGELOG.md`: https://github.com/py-pdf/fpdf2/pull/1285#discussion_r1831582944
* some minor improvements in `docs/Tables.md`

2024-11-11 15:48 UTC, Kaustbh commented
@Lucas-C  please review the commit.

2024-11-12 07:01 UTC, Lucas-C approved these changes

2024-11-12 07:03 UTC, Lucas-C commented
@allcontributors pleasae add @Kaustbh for code

2024-11-12 07:16 UTC, merged

2024-11-12 07:17 UTC, Lucas-C commented
Merged!

Thanks a lot for your contribution @Kaustbh 👍

You have been added to the list of `fpdf2` contributors: https://github.com/py-pdf/fpdf2?tab=readme-ov-file#contributors-

2024-11-12 13:44 UTC, Kaustbh commented
It was a pleasure contributing and I'm honored to be included in the list of contributors. I am looking forward to collaborating more in the future and contributing to more features and improvements.