Handle preceding whitespaces for line break and add corresponding UT
py-pdf/fpdf2 pull request #947
Opened 2023-10-08 06:23 UTC by SaiHarshaK

Fixes#902

This PR adds support to handle text starting with whitespaces which cause linebreak. In case of text with preceding whitespace being added any line with text, this would trigger a linebreak.
The issue currently is that on triggering linebreak, it currently throws an exception since the fragment is basically empty which would mean the [styled_txt_width](https://github.com/py-pdf/fpdf2/blob/a17d2f45f7ca9efb27091f407ea39be731740d25/fpdf/fpdf.py#L2860C11-L2860C11) would be 0, so it would be unable to render anything.

To solve this issue, we add a whitespace so that the fragment is not empty anymore and it able to print whitespace and go ahead with linebreak and continue rendering further output.

Using the repro in the issue, have added UT for the same.
Before code changes:
```
test\text_shaping\test_text_shaping.py:169: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
fpdf\fpdf.py:218: in wrapper
    return fn(self, *args, **kwargs)
fpdf\fpdf.py:3674: in write
    new_page = self._render_styled_text_line(
fpdf\fpdf.py:2831: in _render_styled_text_line
    unscaled_width = frag.get_width(initial_cs=i != 0)
fpdf\line_break.py:179: in get_width
    (char_len, w) = self.font.get_text_width(
fpdf\fonts.py:199: in get_text_width
    return self.shaped_text_width(text, font_size_pt, text_shaping_parms)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = TTFFont(i=2, fontkey=mangal), text = [], font_size_pt = 40
text_shaping_parms = {'direction': None, 'features': {}, 'language': None, 'script': None, ...}

    def shaped_text_width(self, text, font_size_pt, text_shaping_parms):
        """
        When texts are shaped, the length of a string is not always the sum of all individual character widths
        This method will invoke harfbuzz to perform the text shaping and return the sum of "x_advance"
        and "x_offset" for each glyph. This method works for "left to right" or "right to left" texts.
        """
        _, glyph_positions = self.perform_harfbuzz_shaping(
            text, font_size_pt, text_shaping_parms
        )
        text_width = 0
>       for pos in glyph_positions:
E       TypeError: 'NoneType' object is not iterable

fpdf\fonts.py:212: TypeError
```

After code changes:
```
test/text_shaping/test_text_shaping.py::test_mixed_text_shaping PASSED                                       [100%]
```

e.g. Fixes #0 

**Checklist**:

- [ ] The GitHub pipeline is OK (green), 
      meaning that both `pylint` (static code analyzer) and `black` (code formatter) are happy with the changes of this PR.

- [X] A unit test is covering the code added / modified by this PR

- [X] This PR is ready to be merged 

- [] In case of a new feature, docstrings have been added, with also some documentation in the `docs/` folder

- [ ] A mention of the change is present in `CHANGELOG.md`

Since this is a bugfix and not a feature, not adding anything to docs folder. But do i need to add any statement to CHANGELOG.md?

By submitting this pull request, I confirm that my contribution is made under the terms of the [GNU LGPL 3.0 license](https://github.com/py-pdf/fpdf2/blob/master/LICENSE).

2023-10-08 08:49 UTC, gmischler commented
> To solve this issue, we add a whitespace so that the fragment is not empty anymore and it able to print whitespace and go ahead with linebreak and continue rendering further output.

I'm really not sure if this is the correct approach. Why add extra text data that is not actually supposed to appear on page? How can you be sure that this never has any unintended side effects?

It would be much simpler and more logical to just add a check in `shaped_text_width()` and return 0.0 if the fragment is empty.

As a potential source of unwanted interaction: In #897 I am adding functionality to `MultiLineBreak()` so that it can _remove_ any space characters at the start of each line. This is necessary to render converted HTML text correctly.

2023-10-08 08:52 UTC, gmischler requested changes

2023-10-08 08:52 UTC, gmischler commented on fpdf/line_break.py
> +                # add a space
Please don't do that. Fix the problem where it is happening, and don't change the data being processed.

2023-10-08 11:54 UTC, andersonhc commented
@SaiHarshaK 
I agree with gmischler, changing shaped_text_width() to return 0, 0 when harfbuzz returns None is a much simpler and cleaner solution.

2023-10-08 14:46 UTC, SaiHarshaK commented
Got it, that makes sense. will do that and update this PR

2023-10-08 14:58 UTC, SaiHarshaK commented
@andersonhc @gmischler Please check now

2023-10-08 19:25 UTC, gmischler approved these changes

2023-10-09 06:52 UTC, SaiHarshaK commented
@gmischler  @andersonhc is there a way to rerun the tests? i think its complaining some existing test took too long than the limit set.

Not sure why it complains only for a specific version of python, since it ran successfully some versions on windows

2023-10-09 11:26 UTC, SaiHarshaK commented
Thanks, it seems the reruns got these passed :)

2023-10-09 11:29 UTC, Lucas-C commented
> @gmischler @andersonhc is there a way to rerun the tests? i think its complaining some existing test took too long than the limit set.
> 
> Not sure why it complains only for a specific version of python, since it ran successfully some versions on windows

This is a reccuring problem that have, tracked in https://github.com/py-pdf/fpdf2/issues/923

I re-run the pipeline, and everything is ✅ now.

2023-10-09 11:31 UTC, SaiHarshaK commented
Can you get this merged @Lucas-C

2023-10-09 11:41 UTC, Lucas-C commented
> Can you get this merged @Lucas-C

I'll defer to @gmischler on this, as he is much more expert than me on the subject,
and I would not want this PR to conflict with his work in #897.

By the way, are you taking part to [Hacktoberfest ](https://hacktoberfest.com) @SaiHarshaK?
Is it important for you that this PR gets merged in October, if possible?

2023-10-09 18:54 UTC, gmischler commented
> I'll defer to @gmischler on this, as he is much more expert than me on the subject,
> and I would not want this PR to conflict with his work in #897.

Actually, @andersonhc is the real expert here, as I haven't really touched the text shaping stuff.
Neither does #897 touch it, so there won't be any conflict.

2023-10-11 03:36 UTC, andersonhc commented
@allcontributors please add SaiHarshaK for code

2023-10-11 04:35 UTC, merged

2023-10-11 04:35 UTC, SaiHarshaK commented
Thank you!

2023-10-13 11:17 UTC, Lucas-C commented
Thank YOU for your contribution to `fpdf2` @SaiHarshaK 🙂